### PR TITLE
Explicit host header trumps host implied in url

### LINKED ISSUE #245: An explicit host header is ignored if the request url has no implicit host
In the code below, the `options.headers.host` header value will be disregarded and replaced with either: 1) the host implied by the url; or 2) an empty (`''`) value. The resulting `Host` header will then be invalid. Further, it is possible that there is ambiguity which `Host` header is used if the `options.header.Host` was set, given that we don't consider header casing.

https://github.com/hapijs/wreck/blob/e4be576bf35748b32a1088bb0b99eabb01b13dd1/lib/index.js#L131-L132

This breaks any use-case where `wreck` is being used as a reverse proxy and the full downstream url is not being reconstructed and passed in as the target url. As a result, `h2o2` is likely affected as well.

**Affected versions**:

- `wreck@14.2.0` (latest version in `14.x` has this regression)
- `wreck@15.0.0`
- `@hapi/wreck@15.0.0`

**Reproduction**:

```js
//@ts-check
"use strict";

const Fs = require("fs");
const Http = require("http");
const Wreck = require("wreck");
const Util = require("util");

const unlink = Util.promisify(Fs.unlink);

async function main() {
  const server = Http.createServer((req, res) => {
    res.writeHead(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify(req.headers.host));
  });
  const socketPath = "/tmp/wreck-bug-repro.sock";
  const host = "myhost";

  try {
    await unlink(socketPath);
  } catch (err) {
    if (err.code !== "ENOENT") throw err;
  }

  await new Promise(resolve => server.listen(socketPath, resolve));

  let res;

  // This works
  res = await Wreck.get(`http://${host}/path`, {
    json: true,
    socketPath
  });

  console.log(res.payload === host ? "✅ %s === %s" : "❌ %s !== %s", res.payload, host, 'With the host in the request url')

  // This fails
  res = await Wreck.get(`/path`, {
    headers: {
      host,
    },
    json: true,
    socketPath
  });

  console.log(res.payload === host ? "✅ %s === %s" : "❌ %s !== %s", res.payload, host, 'With no host in the request url but a host header via options')

  await new Promise((resolve, reject) => server.close(err => err? reject(err) : resolve()));
}

main().then(
  () => {
    process.exit(0);
  },
  err => {
    console.trace(err);
    process.exit(1);
  }
);
```

### PR DESCRIPTION
**Pull request by ggoodman**
Fixes #245.

### CODE REVIEW

File: test/index.js [hunk 1]
```diff
@@ -1000,6 +1000,20 @@ describe('options.baseUrl', () => {
         expect(promise.req._headers.host).to.equal('localhost:8080');
     });
 
+    it('uses lower-case host header when path is not a full URL', async () => {
+
+        const promise = Wreck.request('get', '/foo', { baseUrl: 'http://localhost:0/', headers: { Host: 'localhost:8080' } });
```
Comment (geek) [inline test/index.js]: this might be a typo, should it be `host` instead of `Host`

File: test/index.js [hunk 2]
```diff
@@ -2013,19 +2027,19 @@ describe('Defaults', () => {
         const wreckB = Wreck.defaults(optionsB);
         const wreckAB = wreckA.defaults(optionsB);
 
-        const promise1 = wreckA.request('get', 'http://no_such_host_error/', { headers: { banana: 911 } });
+        const promise1 = wreckA.request('get', 'http://127.0.0.1:0/', { headers: { banana: 911 } });
```
Comment (geek) [inline test/index.js]: why did this need to change?

Comment (ggoodman) [reply test/index.js]: All of these tests were failing unpredictably on my machine because it was attempting to resolve that address and then connect. It seemed like `expect(promise).to.throw()` was not getting the rejection fast enough, resulting in the tests failing for opaque reasons unrelated to the behaviour they were testing.

File: test/index.js (hunk 1 above)
Comment (ggoodman) [reply test/index.js]: Nice catch. Fixed in 932f1fd.
