### PR TITLE
fix(json): allow numbers in mime fixes #176

### LINKED ISSUE #176: Content-Type not passing the regular expression for JSON smart parse
Hi, 

I have a problem where contentful is returning me a `Content-Type: application/vnd.contentful.delivery.v1+json` but the regex doesn't pass and `wreck.read` returns the buffer instead of parsing it. `json: force` does the trick, but I think the regex should be updated. :)

https://regex101.com/r/ZX6nwW/1

### PR DESCRIPTION
**Pull request by AdriVanHoudt**

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -17,7 +17,7 @@ const Tap = require('./tap');
 // Declare internals
 
 const internals = {
-    jsonRegex: /^application\/[a-z.+-]*json$/,
+    jsonRegex: /^application\/[a-z0-9.+-]*json$/,
```
Comment (geek) [inline lib/index.js]: Maybe 
`/^application\/([a-z0-9.]*[+-]json|json)$/`
to avoid `application/blahjson` returning true? Likely an edge case, but seems reasonable to prevent
